### ISSUE TITLE
Default values for rich type variables

### ISSUE THREAD

**Issue by hyder** [hashicorp/terraform-guides#138]
When defining rich type variables, is it possible to specify a default value just like for string in the example below?

variable "label" {
  type    = "string"
  default = "dev"
}

**Comment by arthuroz** [comment]
Requested here https://github.com/hashicorp/terraform/issues/19898

**Comment by rberlind** [comment]
@hyder : sorry for the very long delay responding to your post.
In Terraform 0.12 and above, you CAN give default values for complex variable types like lists.  For an example, see https://www.terraform.io/docs/language/values/variables.html#declaring-an-input-variable
