### ISSUE TITLE
EKS VPC requires 'enable_dns_hostnames'

### ISSUE THREAD

**Issue by dmathieu** [hashicorp/terraform-guides#157]
Hi,

I'm filing this issue to report a problem with the [AWS EKS Introduction](https://learn.hashicorp.com/terraform/aws/eks-intro) guide. I know it's not in this repository, but I'm not finding any other way to suggest changes to those guides.

The guides creates a VPC with the following:

```
resource "aws_vpc" "demo" {
  cidr_block = "10.0.0.0/16"

  tags = "${
    map(
     "Name", "terraform-eks-demo-node",
     "kubernetes.io/cluster/${var.cluster-name}", "shared",
    )
  }"
}
```

EKS VPCs need the `enable_dns_hostnames` option to be true.

```
resource "aws_vpc" "demo" {
  cidr_block = "10.0.0.0/16"
  enable_dns_hostnames = true

  tags = "${
    map(
     "Name", "terraform-eks-demo-node",
     "kubernetes.io/cluster/${var.cluster-name}", "shared",
    )
  }"
}
```

See https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html
> Your VPC must have DNS hostname and DNS resolution support. Otherwise, your worker nodes cannot register with your cluster.

**Comment by mocofound** [comment]
💯  Thanks for letting us know.  I've relayed the info to the appropriate folks.  The AWS EKS Introduction Learn page is indeed in the process of being refreshed.

In the meantime, if anyone is looking for the correct IAM roles and other things identified by @bodgit they can be found in the updated repo that underpins the guide, here:  https://github.com/terraform-providers/terraform-provider-aws/tree/master/examples/eks-getting-started

This repo includes other interesting configs, for example using a node group the worker nodes.
