### ISSUE TITLE
Could you please elaborate more on why a "Hashistack" cluster practice?

### ISSUE THREAD

**Issue by gerardmrk** [hashicorp/terraform-guides#179]
What are the implications of having this cluster setup, where:

3 server nodes where each node has a Vault, Consul, and Nomad agent running in **Server** mode,

and 

3 client nodes, where each node has a Vault, Consul, and Nomad agent running in **Client** mode.

I would be able to sit down and think of some obvious repercussions, but it would be great if someone more qualified on the matter could elaborate on the whats and whys, and if this is more about conventions and antipatterns than it is about actual risks and potential issues. Thanks in advance.

**Comment by stenio123** [comment]
Hello, this is only for demonstration purposes and it is not best practice.

For production deployments you should have separation of concerns, where your Vault cluster, Consul cluster and Nomad cluster are separate and independent.

A reference for production deployments can be found here:
Vault: https://learn.hashicorp.com/vault/operations/ops-reference-architecture
Consul: https://learn.hashicorp.com/consul/datacenter-deploy/reference-architecture
Nomad: https://www.nomadproject.io/guides/install/production/reference-architecture.html

Following this idea, the Consul cluster used for Vault backend and a Consul cluster for service discovery, etc should also be separate and independent - it makes it easier to manage in a real world scenario. The implications of deploying all three in the same node is that they are three different processes with different responsibilities and potentially different lifecycles for server update, admin access, etc - having all three together is adequate for a production environment.

Hope this helps!

**Comment by gerardmrk** [comment]
Yes thank you.

My initial suspicions as to why this is dubbed an anti-pattern was resource bottleneck related, which would be a dealbreaker. But I never actually thought about the impact to the different update/upgrade lifecycles for each tool.
