### ISSUE TITLE
Move azure resource group from one subscription to other

### ISSUE THREAD

**Issue by pavankumarda2136** [hashicorp/terraform-guides#183]
Hello, Is there a way to move an azure resource group from one subscription to another subscription in same tenant using Terraform ? Please help.

**Comment by mocofound** [comment]
This is not possible using AzureRM Terraform Provider.  The Terraform provider only accepts one subscription_id arguement at a time.

**Comment by vsai9594** [comment]
@mocofound  can we move a  azure resource from one resource group to another resource group using terraform
