### ISSUE TITLE
Terraforming Physical Machines/Baremetal

### ISSUE THREAD

**Issue by jamesnyika** [hashicorp/terraform-guides#188]
Any examples of Terraforming local infrastructure on premise ? I know cloud is the rage, but there are not many examples of terraforming a set of local servers. 
This is an enhancement request

**Comment by ml4** [comment]
Hello @jamesnyika, thanks for reaching out.  Provision on prem depends on whether you are running APIs on prem which Terraform has providers for.  Are you running VMware?

**Comment by jamesnyika** [comment]
Hi @ml4 . I actually am not. I am starting from an existing clean install of Ubuntu 18.04 LTS and want to move from there. The types of providers I hope to use are going to be for MySQL, Tomcat (or similar web application servers), load balancers/proxies (Consul or HA proxy perhaps).

 I just need to be able to terraform on-premise physical servers that will run either
 1. These providers directly (ie. no containers or virtualization of any kind) 
 2. Kubernetes (which I know terraform can do through helm or other providers)

Thank you for the rapid response by the way

**Comment by ml4** [comment]
Are you using open source or enterprise?

**Comment by jamesnyika** [comment]
Open source only.

**Comment by ml4** [comment]
OK Terraform automates APIs.  That's it's primary function.  If you look at the [providers](https://www.terraform.io/docs/providers/index.html) page, you can see the list of APIs it can automate.  

To use Terraform with physicals, and if I understand your post correctly, you have physicals on which you would like to schedule workloads.  An example of the way this would happen is to have installed platform(s) such as OpenStack, which is capable of receiving instructions from TF and orchestrating the delivery of those resources on those physicals.  Does that make sense?

**Comment by jamesnyika** [comment]
Makes sense. I will load up a kubernetes stack to which I will direct terraforming

**Comment by jamesnyika** [comment]
No further input here.  Thanks
