### ISSUE TITLE
EKS introduction is a bit messed up

### ISSUE THREAD

**Issue by bodgit** [hashicorp/terraform-guides#190]
Much like #157 I'm not entirely sure where best to raise this issue, this was the best place I could find.

The [AWS EKS Introduction](https://learn.hashicorp.com/terraform/aws/eks-intro) guide seems to have suffered from bitrot, in particular the IAM roles don't seem to make sense now. The worker node IAM role now appears to be a duplicate of the cluster role in that it has the same name and the same policies attached as the cluster, when it should have the CNI policy, etc. attached instead. Also the wrong IAM role is interpolated in the ConfigMap near the end; it references the cluster IAM role instead of the worker role which results in no obvious errors but the workers cannot access the API to join the cluster as they are unauthorized.

While it's a good learning experience to work out what's wrong and fix it, I suspect this wasn't the original intent of the guide. If there's a more suitable repo to migrate this issue to, and/or the source for the document I'm happy to try and submit a PR.

**Comment by mocofound** [comment]
💯  Thanks for letting us know.  I've relayed the info to the appropriate folks.  The AWS EKS Introduction Learn page is indeed in the process of being refreshed.

In the meantime, if anyone is looking for the correct IAM roles and other things identified by @bodgit they can be found in the updated repo that underpins the guide, here:  https://github.com/terraform-providers/terraform-provider-aws/tree/master/examples/eks-getting-started

This repo includes other interesting configs, for example using a node group the worker nodes.
