### ISSUE TITLE
Support for governance with tfplan, tfconfig and tfstate in v2

### ISSUE THREAD

**Issue by mkjmdski** [hashicorp/terraform-guides#191]
Hi @rberlind!
Recently Hashicorp has published new version of Sentinel imports which seems really interesting feature. Are you going to publish new version of common-functions which we could use with "tfplan/v2" and others?

**Comment by rberlind** [comment]
Hi @mkjmdski :  Yes, I definitely plan on doing this in the near future.  Unfortunately, other job responsibilities have prevented me from doing it sooner.  I hope to do it in the next few weeks. It is also the case that the use of the v2 Sentinel imports will reduce the need for some functions.

Additionally, in April we will have Sentinel modules which will allow a policy to import a Sentinel function without having to copy the body of it.  That will be another big improvement.

**Comment by rberlind** [comment]
@mkjmdski :  This is very late, but I hope you have seen the third-generation Sentinel policies and common functions that DO use the new v2 imports.

I suggest reviewing https://github.com/hashicorp/terraform-guides/blob/master/governance/third-generation/README.md
