### ISSUE TITLE
Explain what Third Gen governance tests are

### ISSUE THREAD

**Issue by mikegreen** [hashicorp/terraform-guides#203]
https://github.com/hashicorp/terraform-guides/tree/master/governance

Can we get a readme update on what the 3rd gen is/does and why better/different than 2nd?

**Comment by rberlind** [comment]
@mikegreen : see https://github.com/hashicorp/terraform-guides/blob/master/governance/third-generation/README.md#important-characterizations-of-the-new-policies

Also see a [Medium post](https://medium.com/hashicorp-engineering/using-new-sentinel-features-in-terraform-cloud-c1ade728cbb?source=friends_link&sk=d77481ec8c9997b584bd5d50dcbbe14a) I wrote about the third generation policies and their use of the v2 imports and Sentinel modules.
