### ISSUE TITLE
This method cannot be used with the terraform s3 backend

### ISSUE THREAD

**Issue by woz5999** [hashicorp/terraform-guides#28]
This example works great with the local state backend, but if you're using S3 as your remote state, you can't set the backend configuration using the generated credentials. 

For example, this project:
```
terraform {
  backend "s3" {
    access_key = "${data.vault_aws_access_credentials.creds.access_key}"
    secret_key = "${data.vault_aws_access_credentials.creds.secret_key}"

    bucket     = "tfstate"
  }
}

provider "vault" {}

data "vault_aws_access_credentials" "creds" {
  backend = "aws"
  role    = "terraform"
}

provider "aws" {
  access_key = "${data.vault_aws_access_credentials.creds.access_key}"
  secret_key = "${data.vault_aws_access_credentials.creds.secret_key}"
}
```

throws the error: 

> Error loading backend config: 1 error(s) occurred:
>
>* terraform.backend: configuration cannot contain interpolations

This is apparently a known issue with terraform backends https://github.com/hashicorp/terraform/issues/15131.

This would have been a great solution, but without some other process to insert credentials for the s3 backend out-of-band, is unworkable.

**Comment by bensojona** [comment]
@woz5999 - it looks like that's an unfortunate limitation at this point. I'd track that issue for the time being for s3 backend enhancements.

As a potential (hacky) workaround, could you use [envconsul](https://github.com/hashicorp/envconsul) to populate the AWS keys from Vault as environment variables and run Terraform as a subprocess?

**Comment by woz5999** [comment]
Thanks for the suggestion. We ended up writing a simple vault client that can inject credentials into the environment and ~/.aws/credentials and integrated that into our terraform workflow.

**Comment by bensojona** [comment]
Ah cool, yeah that sounds similar to envconsul/consul-template (if you prefer not to maintain the client) - good to hear you found a workaround!

**Comment by awstooling** [comment]
> Thanks for the suggestion. We ended up writing a simple vault client that can inject credentials into the environment and ~/.aws/credentials and integrated that into our terraform workflow.

are you able to share more details?
