### ISSUE TITLE
I have an update for the require latest modules policy check but, doesn't account for public registry.

### ISSUE THREAD

**Issue by roknsound** [hashicorp/terraform-guides#299]
For policy check: https://github.com/hashicorp/terraform-guides/blob/master/governance/third-generation/cloud-agnostic/http-examples/use-latest-module-versions.sentinel

Currently that policy check doesn't pull all modules, this function will allow you to pull all of them but, doest account for public module registry. As it would break certain usages of the original policy because of the lack of support for public module registry, I have created this as an issue instead of a PR on the policy. 

@rberlind thought this might useful.

```sentinel
get_modules = func(url, modules) {
  req = http.request(url)
  req = req.with_header("Authorization", "Bearer " + token)
  res = json.unmarshal(http.get(req).body)
  # Iterate over the modules and extract names, providers, and latest versions
  for res.modules as m {
    index = m.namespace + "/" + m.name + "/" + m.provider
    modules[index] = m.version
  }
  for keys(res.meta) as attr{
    if attr == "next_url" {
      if int(res.meta.next_offset) > 0 {
        return get_modules(address + "/api/registry/v1/modules/" + organization + "?namespace=clover&offset=" + string(res.meta.next_offset), modules)
      }
    }
  }
  return modules
}
```

**Comment by rberlind** [comment]
@roknsound :  This is very timely because I planned to update this policy to handle pagination so it can examine all modules in both the public registry and in private module registries.  I hope to do that this week and will consider your suggested code when doing so.

**Comment by rberlind** [comment]
@roknsound :  I used some of your approach in https://github.com/hashicorp/terraform-guides/pull/301 which now does pagination for Private Module Registries.  I intentionally did not do pagination for the public registry.  See the updated policy and README.md file.  Note that the policy does not yet retrieve "publically curated modules" which are modules in the public registry exposed through a private registry (PMR).  That would require using a different API endpoint which is not yet supported on older versions of TFE.  But I plan to add a version of the policy that does use that.
