### ISSUE TITLE
remote: error: File .terraform/providers/registry.terraform.io/hashicorp/azurerm/2.5.0/darwin_amd64/terraform-provider-azurerm_v2.5.0_x5 is 149.41 MB; this exceeds GitHub's file size limit of 100.00 MB

### ISSUE THREAD

**Issue by tekenthusiast** [hashicorp/terraform-guides#311]
This command works well:
`git filter-branch -f --index-filter 'git rm --cached -r --ignore-unmatch .terraform/'`

_Originally posted by @riouruma in https://github.com/hashicorp/terraform-guides/issues/92#issuecomment-805563050_

**Comment by spencercg** [comment]
Really helped, thank you
