### ISSUE TITLE
Plan to split out the sentinel policies?

### ISSUE THREAD

**Issue by fwang001** [hashicorp/terraform-guides#314]
Hi there,

Firstly, thank you very much for your huge effort on this repo. A lot of people and orgs benefited from this, and I'm sure they want to also contribute back. So my question is, Is there any plan to split out the "governance" folder as a standalone repo (focusing on sentinel policies) so that people can contribute back more useful/common/shared policies? The problem I can see based on our usage is, we have to do copy/paste the sub folder of the "governance" folder and keep maintain it forever. And as you can imagine there could be a huge of duplicated effort from the organizations if they want to implement the same policies.  @rberlind  @bensojona Thoughts?

**Comment by rberlind** [comment]
@fwang001 : Splitting out the Sentinel policies into a separate repository under the hashicorp organization would indeed make sense, but also poses some challenges since various documents refer to their current location.  Perhaps we could create a new repository such as hashicorp/terraform-governance and add any new policies to that and gradually point other docs and workshops to the new repository.

@bensojona : what do you think?

**Comment by fwang001** [comment]
> @fwang001 : Splitting out the Sentinel policies into a separate repository under the hashicorp organization would indeed make sense, but also poses some challenges since various documents refer to their current location. Perhaps we could create a new repository such as hashicorp/terraform-governance and add any new policies to that and gradually point other docs and workshops to the new repository.
> 
> @bensojona : what do you think?

Thank you for the feedback, @rberlind Another scenario I forgot to mention is supporting more vendors, so more policies could be contributed for DigitalOcean, OVH, OpenStack, Megaport, etc etc.

**Comment by rberlind** [comment]
@fwang001 : The repository is a public repository, so non-HashiCorp people can contribute additional policies if desired as long as they adhere to the current third-generation style and use the common functions and also include test cases and mocks for all policies.

Before we create a new repository with the Sentinel policies only, I would like to better understand why that is necessary for you. It is certainly possible for you or any customer to fork the current terraform-guides repository and then point your policy sets in Terraform Cloud or Terraform Enterprise against your fork.  You can also sync changes to this repository into your fork periodically.  Even if we did create a new hashicorp/terraform-governance repository, you would probably still want to fork it to protect yourself from changes made by HashiCorp or other people inadvertantly affecting your policies in a negative way.

**Comment by fwang001** [comment]
Hi @rberlind  thank you for replying. I do understand people from non-Hashicorp can still contribute additional policies to this repo. However, the overall repo is not designed for the Sentinel policy management. It's mostly like a documentation repo, right?

I have been working on OpenStack and Kubernetes community in the last 10 years. In my opinion, both OpenStack and Kubernetes have a fantastic built-in pluggable mechanism to support vendors and also make it easier to user to deploy with the right driver (e.g. a storage driver from IBM or EMC). I can see Sentinel has already got a good pluggable capability as well, each policy can be a 'building-block', user can 'assemble' them based on their requirements to fit dev/test, preprod and prod environments. So I would like to see we can do something similar to 

So I believe building a more contribution-friendly repo for collaborating is critical to encourage the adoption of Sentinel, which will provider several benefits for both Hashicorp and the community:

- Encourage the adoption of Sentinel
- Encourage the contribution from vendors
- Avoid duplicated effort of creating user's own policies
- ...

I just found this repo https://github.com/hashicorp/terraform-foundational-policies-library from the Terraform Cloud dashboard. And I think it's kind of what I want. But seems it only focus on CIS. So it brings in another challenge, user cannot apply multi policy repos on the Terraform Cloud dashboard via the policy set.

Overall, I would like to a joint collaboration to work out a repo people can work together.

**Comment by rberlind** [comment]
@fwang001 : I have created a new repository, https://github.com/hashicorp/terraform-sentinel-policies, that only contains the third generation policies, common functions, and associated mocks and test cases.  

I also made some improvements by stripping out all unneeded data such as planned_values and raw collections from the tfplan/v2 mocks and adding links at the top of the doc files for the Sentinel modules pointing to the actual line in the Sentinel module giving the code for the documented function.  (I have only done that so far for tfconfig-functions, tfplan-functions, and tfrun-functions; but I will add links to the other module doc files later today.)

I hope this gives you what you want.

**Comment by rberlind** [comment]
@fwang001 : I completed adding links from the other Sentinel module documentation (md) files to the lines of code in the modules where they start.  I also published a v1.0.0 release for the new repository.

**Comment by rberlind** [comment]
Also, all of my own Sentinel slides and Instruqt tracks have been updated to refer to the new repository instead of this one.

**Comment by fwang001** [comment]
@rberlind thank you for the quick action. Did you see issue I opened in https://github.com/hashicorp/terraform-foundational-policies-library/issues/47 That's sort of an example that duplicated effort is happening. Is there any possibility that we can combine the effort together? Or you think it's better keep the work separated?

Based on my knowledge of TFC+Sentinel, there is no way to specify multi policy sets. So from a user perspective, the best way to apply policies from multi sources (e.g. policies from https://github.com/hashicorp/terraform-sentinel-policies and policies from https://github.com/hashicorp/terraform-foundational-policies-library) is creating user's own repo and defining the sentinel.hcl and link the policies by remote URL. Am I correct? 

Therefore, if there is any new policy user want to introduce, they will contribute it back to upstream community, and then as long as it merged (sure, they can keep it in local during the policy being reviewed), then can just add it in sentinel.hcl and link it back. I'm thinking of writing a user guide (beast practices) for any potential consumer of this repo. Thoughts and comments will be appreciated.

**Comment by fwang001** [comment]
Hi @rberlind, thank you for your reply and I think that does make sense for me. I'm sorry to see you're leaving Hashicorp but I believe that would be good for you and wish you will be successful on your new role.

So I'm wondering after your leaving, will repo https://github.com/hashicorp/terraform-sentinel-policies be actively maintained ?

**Comment by rberlind** [comment]
Yes, @fwang001 : I do expect that the new terraform-sentinel-policies repository will be maintained by members of the HashiCorp solutions engineering (SE) team.

**Comment by fwang001** [comment]
> Yes, @fwang001 : I do expect that the new terraform-sentinel-policies repository will be maintained by members of the HashiCorp solutions engineering (SE) team.

Thank you very much, @rberlind  and I wish you all the best on your new journey. Cheers.
