### ISSUE TITLE
Is it possible to scan multiple resources?

### ISSUE THREAD

**Issue by shaneschnell** [hashicorp/terraform-guides#318]
It would be nice to be able to add multiple types of GCP resources. 

instead of this:
```
allGCEInstances = plan.find_resources("google_compute_instance")
```

Something like this:
```
resource_types = ["google_compute_instance", "google_storage_bucket"]
allGCEInstances = plan.find_resources(resource_types)
```

https://github.com/hashicorp/terraform-guides/blob/014d7056dbc9f0ab372303700f7e7da3d0a1a294/governance/third-generation/gcp/enforce-mandatory-labels.sentinel#L15

**Comment by rberlind** [comment]
@shaneschnell : Thanks for the suggestion.  While we could possibly create a `find_multiple_resources` function to find multiple resource types, a problem is that the `find` functions are usually followed by `filter` functions which examine specific attributes of the resources found by the `find` functions.  If we found multiple resource types, they might not share the same attribute targeted by the `filter` function.  In any case, you can always invoke the `find_resources` function multiple times for different resource types, with each occurence followed by a `filter` function specific to that resource type.

But if you have a specific example of an attribute that would be shared by "google_compute_instance" and "google_storage_bucket" that would then be filtered with a single `filter` function, please let us know.

**Comment by shaneschnell** [comment]
@rberlind I created a PR here:
https://github.com/hashicorp/terraform-guides/pull/319

Let me know what you think.

**Comment by rberlind** [comment]
Fixed https://github.com/hashicorp/terraform-guides/pull/319

**Comment by rberlind** [comment]
I also added this to https://github.com/hashicorp/terraform-sentinel-policies
