### ISSUE TITLE
Nomad not registered with consul

### ISSUE THREAD

**Issue by sloan-dog** [hashicorp/terraform-guides#52]
After provisioning all infrastructure as defined in 'best practices' example, `nomad` is not listed when executing `consul catalog services` from the bastion host and is not registered. Using all default settings. 

Running in us-west-2

**Comment by bensojona** [comment]
@sloan-dog - Can you run the below commands and send a gist with the output from the commands?

1. `consul version`
1. `nomad version`
1. `sudo systemctl status consul`
1. `sudo systemctl status nomad`
1. `consul members`
1. `consul info`
1. `nomad server members`
1. `nomad node status`

**Comment by sloan-dog** [comment]
@bensojona 

Thanks for the prompt reply! Looks like nomad service died 
https://gist.github.com/sloan-dog/7f9172565bd63dd1a7345d6a571ae2b8

**Comment by bensojona** [comment]
@sloan-dog I'm assuming you're running these commands from the Bastion host, correct?

If that's the case, the Nomad agent being stopped on the Bastion host makes sense as that Nomad agent is configured to just pass through requests to the Nomad server cluster and doesn't need to be running. It seems the reason the pass through of requests is not working is it's configured to find the remote Nomad cluster through Consul (`nomad.service.consul`), which it can't because Nomad never registered. You can see this [here](https://gist.github.com/sloan-dog/7f9172565bd63dd1a7345d6a571ae2b8#file-sh-L87-L91).

Can you ssh into one of the `hashistack-best-practices-hashistack` nodes and run those same Nomad commands?

Should be something like `ssh -A ubuntu@10.139.12.145` or `ssh -A ec2-user@10.139.12.145` (depending on if you provisioned a rhel or ubuntu box). That command should work if you `ssh-add`'d the key locally and ssh'd into the Bastion host using the `-A` switch.

**Comment by sloan-dog** [comment]
@bensojona Yes. I'm executing on bastion host (RHEL). nodes are also (RHEL)

Okay, I ran those  same commands on a hashistack node ->
https://gist.github.com/sloan-dog/3357bf67050813f765a96089ed8088c0

**Comment by sloan-dog** [comment]
Just for fun...I ran `nomad node status` on another hashistack host and output is 
```
[ec2-user@hashistack-best-practices-hashistack-i-0c39c3db7e012340c ~]$ nomad node status
Error querying node status: Get https://127.0.0.1:4646/v1/nodes: dial tcp 127.0.0.1:4646: connect: connection refused
```

**Comment by bensojona** [comment]
Hm yeah - looks like the Nomad agents aren't starting. Can you try restarting one (`sudo systemctl restart nomad`), and if that works, do the rest?

You can check the logs of the Nomad service via `sudo journalctl -u nomad.service`.

**Comment by sloan-dog** [comment]
@bensojona I ran this `sudo journalctl -u nomad` on a hashistack host. 

Take a look at the output here https://gist.github.com/sloan-dog/acf973ee168f30a2286c9e7777e62859#file-output-sh-L92

Looks like an issue with decoding a cert

**Comment by sloan-dog** [comment]
Restarting runs into the same issue when parsing cert

**Comment by bensojona** [comment]
Can you send me the config files in `/etc/nomad.d/.` and verify the certs exist in the directories specified in the config?

**Comment by bensojona** [comment]
In addition to verifying the certs exist, can you verify that they were written and formatted properly?

**Comment by sloan-dog** [comment]
@bensojona [ec2-user@hashistack-best-practices-hashistack-i-0c39c3db7e012340c nomad.d]$ pwd
/etc/nomad.d
[ec2-user@hashistack-best-practices-hashistack-i-0c39c3db7e012340c nomad.d]$ ls
default.hcl  nomad.conf

Default.hcl -> https://gist.github.com/sloan-dog/c5c2713a0f7f83e18cc82ea9dff33a77

nomad.conf is completely empty. 

What is the best strategy for verifiying the certs. 

All three are at least present 
```
  ca_file    = "/opt/nomad/tls/consul-ca.crt"
  cert_file  = "/opt/nomad/tls/consul.crt"
  key_file   = "/opt/nomad/tls/consul.key"
```

**Comment by sloan-dog** [comment]
`openssl rsa -in nomad.key -check` -> validates succesfully
`openssl x509 -in nomad.crt -text -noout` -> is able to parse
`openssl x509 -in nomad-ca.crt -text -noout` -> is able to parse

**Comment by sloan-dog** [comment]
By process of elimination (renaming certs), i discovered the problem cert is `/opt/nomad/tls/nomad-ca.crt`

**Comment by bensojona** [comment]
Empty `nomad.conf` file is expected. Are you just running the [vanilla best-practices repo](https://github.com/hashicorp/terraform-guides/tree/master/infrastructure-as-code/hashistack/best-practices/terraform-aws), or did you change any variables or TF in that folder?

I run the below to check certs usually, first one will be the interesting one.

```
openssl verify -CAfile /opt/nomad/tls/nomad-ca.crt
openssl x509 -text -in /opt/nomad/tls/nomad.key
openssl x509 -text -in /opt/nomad/tls/nomad-ca.crt
```

**Comment by bensojona** [comment]
Can you also run `cat /etc/profile.d/nomad.sh`

**Comment by sloan-dog** [comment]
@bensojona I am running vanilla. Nothing changed from master @ https://github.com/hashicorp/terraform-guides/tree/master/infrastructure-as-code/hashistack/best-practices/terraform-aws

**Comment by bensojona** [comment]
Did `openssl verify -CAfile /opt/nomad/tls/nomad-ca.crt` come back clean?

**Comment by bensojona** [comment]
Oh also - which version of Terraform are you running?

**Comment by sloan-dog** [comment]
Terraform v0.11.8

**Comment by sloan-dog** [comment]
`openssl verify -CAfile /opt/nomad/tls/nomad-ca.crt /opt/nomad/tls/nomad.crt` returns `/opt/nomad/tls/nomad.crt: OK`. 

Running `openssl verify -CAfile /opt/nomad/tls/nomad-ca.crt` just hangs...?

**Comment by sloan-dog** [comment]
and here's another variation ->
```
[ec2-user@hashistack-best-practices-hashistack-i-0c39c3db7e012340c ~]$ openssl verify -verbose /opt/nomad/tls/nomad-ca.crt
/opt/nomad/tls/nomad-ca.crt: O = Example Inc., CN = example.com
error 18 at 0 depth lookup:self signed certificate
OK
```

**Comment by bensojona** [comment]
Ah yes, forgot to include the lead cert in that statement.

Okay - so I was able to reproduce. Assuming you got that same CA cert as me, remove the blank line at the end of it. No idea how it started adding an extra blank line, but that seems to have resolved it for me.

**Comment by sloan-dog** [comment]
@bensojona HOLY SHIT BROTHER, good catch. Yea, that did the trick. 

Thank you for the assist. This has been the most lit github conversation! That cert file is generated somewhere, maybe will add a step to trim the last line...if it is empty

**Comment by bensojona** [comment]
I found it, it's in this module --> https://github.com/hashicorp-modules/tls-self-signed-cert

It must have always added the extra line, I'm guessing a more recent version of Nomad trips on it where it didn't before. Seems to work fine still for Consul and Vault. Will update the module and cut a new release.

**Comment by bensojona** [comment]
[chomp](https://www.terraform.io/docs/configuration/interpolation.html#chomp-string-) should take care of it.

**Comment by sloan-dog** [comment]
Think its something in this module -> https://github.com/hashicorp-modules/tls-self-signed-cert

**Comment by sloan-dog** [comment]
Oh...yep, you already arrived at that conclusion...nvm

**Comment by bensojona** [comment]
Alright, should be fixed with this release --> https://github.com/hashicorp-modules/tls-self-signed-cert/releases/tag/v0.1.2

Do a `terraform get -update` and try again, should be resolved (worked for me).
