### ISSUE TITLE
No Azure version of governance/aws/enforce-mandatory-tags.sentinel

### ISSUE THREAD

**Issue by tomisaacson** [hashicorp/terraform-guides#83]
There's no Azure equivalent of https://github.com/hashicorp/terraform-guides/blob/master/governance/aws/enforce-mandatory-tags.sentinel

**Comment by rberlind** [comment]
@tomisaacson :  we communicated about this issue in your PR a long time ago.
But I was going through all the issues in this repository and wanted to let you know about the current version of a policy that does enforce mandatory tags for Azure: https://github.com/hashicorp/terraform-guides/blob/master/governance/third-generation/azure/enforce-mandatory-tags.sentinel

Roger Berlind
Global Technology Specialist
HashiCorp
