### ISSUE TITLE
Unable to ignore .terraform before pushing to GitHub

### ISSUE THREAD

**Issue by nguyendviet** [hashicorp/terraform-guides#92]
I have an error that prevents me from pushing my changes to my GitHub repo:

`remote: error: File .terraform/plugins/darwin_amd64/terraform-provider-aws_v2.1.0_x4 is 134.07 MB; this exceeds GitHub's file size limit of 100.00 MB`

I understand the issue is the file is too large to push to github. I've tried adding the whole .terraform folder to my .gitignore file using these guides: [from GitHub](https://github.com/github/gitignore/blob/master/Terraform.gitignore) and [from Hashicorp](https://github.com/hashicorp/terraform-guides/blob/master/.gitignore). My `.terraform` is greyed out in my VSCode.

I've also tried these from several answers on SOF:
```
git rm -r --cached <filePath>
git reset -r -- <filePath>
# rm all files
git rm -r --cached .
# add all files as per new .gitignore
git add .
# now, commit for new .gitignore to apply
git commit -m ".gitignore is now working"
```

I've also tried [this](https://help.github.com/en/articles/removing-files-from-a-repositorys-history#removing-a-file-added-in-the-most-recent-unpushed-commit).

However:
```
$ git rm --cached -r .terraform
fatal: pathspec '.terraform' did not match any files
$ git rm -r --cached ./.terraform
fatal: pathspec './.terraform' did not match any files
$ ls -la
total 216
drwxr-xr-x  15 viet  staff    480 12 Mar 15:07 .
drwxr-xr-x  16 viet  staff    512  7 Mar 14:36 ..
drwxr-xr-x  15 viet  staff    480 12 Mar 15:11 .git
-rw-r--r--   1 viet  staff     66 29 Jan 15:04 .gitattributes
-rw-r--r--   1 viet  staff    933 12 Mar 15:08 .gitignore
drwxr-xr-x   3 viet  staff     96 12 Mar 15:07 .terraform
...
$ git push
Counting objects: 35, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (33/33), done.
Writing objects: 100% (35/35), 26.51 MiB | 5.04 MiB/s, done.
Total 35 (delta 17), reused 0 (delta 0)
remote: Resolving deltas: 100% (17/17), completed with 1 local object.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 9cc1ae0d9a2d56bd6f7e8b4b152a10cd
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File .terraform/plugins/darwin_amd64/terraform-provider-aws_v2.1.0_x4 is 134.07 MB; this exceeds GitHub's file size limit of 100.00 MB
To github.com:nditech/NDI-Demtools.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@github.com:<REPO-NAME>'
```

**Comment by KameronKales** [comment]
Yeah, I've got the same issue. No matter what I Try I can't get it figured out. Would love to know how/if you solved.

**Comment by nguyendviet** [comment]
@KameronKales I ended up removing the folder from the repo then I ran `terraform init` again and it worked. If it doesn't work for you, just delete the repo, clone it down again and run `terraform init`. *It was taking more time than it needed to be to troubleshoot the issue and I had to move on with other tasks.*

**Comment by KameronKales** [comment]
Thanks for the help.

**Comment by okonon** [comment]
I am seeing same issue but re running terraform init does not fix the isseu

**Comment by herms14** [comment]
has there been a fix for this? I'm also getting the same error

**Comment by riouruma** [comment]
This command works well:
`git filter-branch -f --index-filter 'git rm --cached -r --ignore-unmatch .terraform/'`

**Comment by appwebtech** [comment]
> This command works well:
> `git filter-branch -f --index-filter 'git rm --cached -r --ignore-unmatch .terraform/'`

Excellent! A life saver.

**Comment by Madhu-Malempati** [comment]
> This command works well:
> `git filter-branch -f --index-filter 'git rm --cached -r --ignore-unmatch .terraform/'`

Kudos buddy. Saved my time too

**Comment by NiniiGit** [comment]
Other ways to fix this are available on this link:
https://stackoverflow.com/questions/19858590/issues-with-pushing-large-files-through-git

**Comment by chelto** [comment]
> This command works well: `git filter-branch -f --index-filter 'git rm --cached -r --ignore-unmatch .terraform/'`

this worked for aswell. Amazing and saved me loads of time

**Comment by cleitontorres23** [comment]
Thank you very much ;-)

**Comment by Gabegi** [comment]
saved me a lot of time @riouruma :) thanks

**Comment by pdruzdzelreply** [comment]
Thank you!! Worked!

**Comment by pdruzdzelreply** [comment]
> This command works well: `git filter-branch -f --index-filter 'git rm --cached -r --ignore-unmatch .terraform/'`

Thank you!

**Comment by thomassibin94** [comment]
> 

Works perfectly!!

**Comment by Kiran121245** [comment]
> git filter-branch -f --index-filter 'git rm --cached -r --ignore-unmatch .terraform/'

Your a life saver man....:)

**Comment by edwardborges** [comment]
> Este comando funciona bem: `git filter-branch -f --index-filter 'git rm --cached -r --ignore-unmatch .terraform/'`

Mandou muito beem
me salvou também 
Valeu

**Comment by VineetaKhaitan** [comment]
Saved my time too buddy!! Thanks.

**Comment by vinodrc19** [comment]
You are a life saver buddy. At one point, it looked like there is no fix but crude work arounds.

**Comment by koenwillems-tomtom** [comment]
super awsome thanks fixed this at a Friday 17:00 great!

**Comment by Sabya1234** [comment]
> git filter-branch -f --index-filter 'git rm --cached -r --ignore-unmatch .terraform/'
life saviour , thanks for the command

**Comment by deleonab** [comment]
Brilliant! 
git filter-branch -f --index-filter 'git rm --cached -r --ignore-unmatch .terraform/'

Worked for me as well after trying loads of other solutions.

**Comment by eabrahym75** [comment]
Awesome, tried and it worked

**Comment by clarizalooktech** [comment]
git filter-branch -f --index-filter 'git rm --cached -r --ignore-unmatch .terraform/' 

worked for me too!

**Comment by clinton213** [comment]
hey guys, i dont know whats wrong but this doesnt work for me. I get this response 
WARNING: git-filter-branch has a glut of gotchas generating mangled history   
         rewrites.  Hit Ctrl-C before proceeding to abort, then use an
         alternative filtering tool such as 'git filter-repo'
         (https://github.com/newren/git-filter-repo/) instead.  See the
         filter-branch manual page for more details; to squelch this warning,
         set FILTER_BRANCH_SQUELCH_WARNING=1.
Proceeding with filter-branch...

fatal: ambiguous argument 'rm': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

**Comment by bridgetgy** [comment]
live safer... with this git filter-branch -f --index-filter 'git rm --cached -r --ignore-unmatch .terraform/'

**Comment by sshachidixit** [comment]
@clinton213 I am also getting the same issue after running this - git filter-branch -f --index-filter 'git rm --cached -r --ignore-unmatch .terraform/' , is your resolved?

**Comment by leetcarey** [comment]
Any Ideas how to resolve when you have a number of tags you want to upload but appears to have the large file in them also. Master is fixed using the filter-branch command but the tags are unable to be pushed up . Thanks

**Comment by ak7dar** [comment]
> This command works well: `git filter-branch -f --index-filter 'git rm --cached -r --ignore-unmatch .terraform/'`

What a life-saver!

Thanks

**Comment by manahgc** [comment]
> This command works well: `git filter-branch -f --index-filter 'git rm --cached -r --ignore-unmatch .terraform/'`

Excellent, thanks

**Comment by TanuAWSTerra** [comment]
I tried lots of other solution, this command works well
git filter-branch -f --index-filter 'git rm --cached -r --ignore-unmatch .terraform/'

Brilliant!! Thanks

**Comment by rvyom-JNPR** [comment]
@clinton213 make sure you have added the right folder path. Copy the filepath that is creating that error and use this command.

`git filter-branch --index-filter 'git rm -r --cached --ignore-unmatch <file/dir>' HEAD`

**Comment by Kawalyaa** [comment]
Thanks @rvyom-JNPR  using the correct file path worked for me  git filter-branch --index-filter 'git rm -r --cached --ignore-unmatch <file/dir>' HEAD

**Comment by shravankundapur** [comment]
> This command works well: `git filter-branch -f --index-filter 'git rm --cached -r --ignore-unmatch .terraform/'`

i was stuck here for so long, this helped me a lot😍

**Comment by gaikwadpeter** [comment]
Works like charm.............

git filter-branch -f --index-filter 'git rm --cached -r --ignore-unmatch .terraform/'

But deletes the commit history. so be careful before doing this in Company or Corp area.

**Comment by muriello** [comment]
> [@KameronKales](https://github.com/KameronKales) I ended up removing the folder from the repo then I ran `terraform init` again and it worked. If it doesn't work for you, just delete the repo, clone it down again and run `terraform init`. _It was taking more time than it needed to be to troubleshoot the issue and I had to move on with other tasks._

**Comment by muriello** [comment]
Which folder you removed from the repo are you talking about? You only had an empty repo that you created at the beginning to push your code in. Which one did you removed then, for git push to start working? I experienced the same error and i am stuck here. Please respond. Thank you
